require:
  - rubocop-minitest
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'bot_team.gemspec'
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Exclude:
    - 'bot_team.gemspec'
Style/ExpandPathArguments:
  Exclude:
    - 'bot_team.gemspec'