require:
  - rubocop-minitest
AllCops:
  TargetRubyVersion: 3.1.2
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
